language: node_js
node_js:
  # chai and gulp don't support node 0.8... they're only devDependencies...
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'
before_script:
  - npm install -g gulp
script: gulp && npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
